---
- name: Install Clickhouse
  hosts: clickhouse
  tasks:
    - block:
      - name: Get clickhouse distrib
        ansible.builtin.get_url:
          url: "https://packages.clickhouse.com/deb/pool/stable/{{ item }}_{{ clickhouse_version }}_all.deb"
          # url: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.noarch.rpm"
          dest: "./{{ item }}-{{ clickhouse_version }}.deb"
        with_items: "{{ clickhouse_packages }}"
      rescue:
      - name: Get clickhouse distrib
        ansible.builtin.get_url:
          # url: "https://packages.clickhouse.com/rpm/stable/clickhouse-common-static-{{ clickhouse_version }}.x86_64.rpm"
          url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
          dest: "./clickhouse-common-static-{{ clickhouse_version }}.deb"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}"
        state: present
      loop:
        - clickhouse-common-static-{{ clickhouse_version }}.deb
        - clickhouse-client-{{ clickhouse_version }}.deb
        - clickhouse-server-{{ clickhouse_version }}.deb
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
      ignore_errors: true
- name: Install vector
  hosts: vector
  tasks:
    - name: Create vector directory
      become: true
      file:
        path: /vector
        state: directory
        mode: 0644
    - name: Download archive fiile
      become: true
      get_url:
        url: "{{ vector_url }}"
        dest: /vector.tar.gz
        mode: '0440'
    - name: Unpack Vector to local directory
      become: true
      ansible.builtin.unarchive:
        src: /vector.tar.gz
        dest: /vector
        extra_opts:
          - --strip-components=2
        remote_src: yes
    # - name: Unarchive a file that needs to be downloaded (added in 2.0)
    #   ansible.builtin.unarchive:
    #     src: {{ vector_url }}
    #     dest: /vector
    #     remote_src: yes
